import Booking from "../models/Booking.js";
import Payment from "../models/Payment.js";
import axios from "axios";
import { v4 as uuidv4 } from "uuid";

/* ==========================================================================
   CARD CHECKOUT
   ========================================================================== */
export const createCheckout = async (req, res) => {
  try {
    const { bookingId } = req.body;

    const booking = await Booking.findById(bookingId).populate("trip");
    if (!booking) {
      return res.status(404).json({ message: "Booking not found" });
    }

    const transactionId = uuidv4();

    // Use findOneAndUpdate with upsert to prevent unique duplicate errors 
    // if the user refreshes or re-attempts the payment process
    await Payment.findOneAndUpdate(
      { bookingId: booking._id },
      {
        amount: booking.totalAmount,
        method: "card",
        transactionId,
        status: "pending",
      },
      { upsert: true, new: true, setDefaultsOnInsert: true }
    );

    const fakeGatewayUrl = `${process.env.CLIENT_URL}/payment-success?bookingId=${booking._id}&transactionId=${transactionId}`;

    res.json({ paymentUrl: fakeGatewayUrl });
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
};

/* ==========================================================================
   KHALTI PAYMENT
   ========================================================================== */
export const createKhaltiPayment = async (req, res) => {
  try {
    const { bookingId } = req.body;

    const booking = await Booking.findById(bookingId).populate("trip");
    if (!booking) {
      return res.status(404).json({ message: "Booking not found" });
    }

    // Khalti demands amounts in Paisa (1 NPR = 100 Paisa)
    // If totalAmount is already stored in cents/paisa, drop the "* 100" multiplier
    const khaltiAmountInPaisa = Math.round(booking.totalAmount * 100);

    const response = await axios.post(
      "https://a.khalti.com/api/v2/epayment/initiate/",
      {
        return_url: `${process.env.CLIENT_URL}/payment-success`,
        website_url: process.env.CLIENT_URL,
        amount: khaltiAmountInPaisa,
        purchase_order_id: booking._id.toString(),
        purchase_order_name: booking.trip.title,
        customer_info: {
          name: `${booking.buyer.firstName} ${booking.buyer.lastName}`.trim(),
          email: booking.buyer.email,
        },
      },
      {
        headers: {
          Authorization: `Key ${process.env.KHALTI_SECRET_KEY}`,
          "Content-Type": "application/json",
        },
      }
    );

    // CRITICAL FIX: Extract the actual 'pidx' tracking token generated by Khalti
    const { pidx, payment_url } = response.data;

    if (!pidx || !payment_url) {
      throw new Error("Invalid response structural signature returned from Khalti.");
    }

    // Upsert the payment document using Khalti's official pidx token
    await Payment.findOneAndUpdate(
      { bookingId: booking._id },
      {
        amount: booking.totalAmount,
        method: "khalti",
        transactionId: pidx, // Enforced as your lookup reference pointer
        status: "pending",
      },
      { upsert: true, new: true, setDefaultsOnInsert: true }
    );

    res.json({ paymentUrl: payment_url });
  } catch (err) {
    console.error(
      "KHALTI INITIALIZATION ERROR:",
      err.response?.data || err.message
    );

    res.status(500).json({
      message: "Could not initialize Khalti payment gateway transaction context.",
    });
  }
};

// ─────────────────────────────────────────────
// UPDATE PAYMENT STATUS (admin)
// PUT /api/payments/:bookingId/status
// Body: { status: "success" | "pending" | "failed" }
// ─────────────────────────────────────────────

export const updatePaymentStatus = async (req, res) => {
  try {
    const { status } = req.body;

    const allowed = ["pending", "success", "failed"];
    if (!allowed.includes(status)) {
      return res.status(400).json({ message: "Invalid payment status" });
    }

    const payment = await Payment.findOne({ bookingId: req.params.bookingId });

    if (!payment) {
      return res.status(404).json({ message: "Payment not found" });
    }

    payment.status = status;
    await payment.save();

    res.json({
      message: "Payment status updated",
      payment,
    });
  } catch (err) {
    console.error("updatePaymentStatus error:", err);
    res.status(500).json({ message: err.message });
  }
};